lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem'
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase:      ''  # si tu n’as pas mis de mot de passe sur ta clé
    token_ttl:        3600
